### ISSUE TITLE
Script description file should describe script outputs

### ISSUE THREAD

**Issue by senesis** [IsEnesEval/diagstandards#11]
This issue is intended to replace and continue a review discussion which content is :

Contribution by @senesis, requesting to add an entry named 'outputs' in script's description file, with that content:
> A dictionary of patterns  which allows the tool to discover every output file and to assign a label to it. The patterns and the labels used as dictionary keys  can make use of keywords 'variable', 'dataset' and 'reference_dataset'; the tool may instantiate the keywords with all possible values to form file basenames and test whether a corresponding file exists in scripts output directories; dictionary values can be pairs, in which case, the second element of the pair allows for providing a pattern for indicating the output variable's short_name

Reply by @bouweandela :
>I'm not sure if this is the right approach, diagnostic developers may struggle to give their output files the names they would like and may be unable to provide useful metadata about the output files. I would rather go for a standard output metadata format, e.g. the same or very similar to the input metadata format. I would recommend adding things like caption, authors, references, input files used, etc like we do in the ESMValCore: https://docs.esmvaltool.org/projects/esmvalcore/en/latest/interfaces.html#information-provided-by-the-diagnostic-script-to-esmvalcore

@senesis :
> If the tool has no way to predict the list of possible script output files (and to name them) without running the script, it cannot implement a cache of script results (because he must run the script anyway)
This is a basic shortcoming of ESMValTool

**Comment by bouweandela** [comment]
> If the tool has no way to predict the list of possible script output files (and to name them) without running the script, it cannot implement a cache of script results (because he must run the script anyway)

All the tool needs to know to create a cache of script results (should such a feature be deemed desirable at some point) is that the script ran successfully, there is no need to check that every individual output file exists. Unless users go and delete some script output files of course. But supporting that in a meaningful way would mean that every diagnostic developer will need to go and implement code to deal with regenerating some results and skipping others and I feel that that is more than we can ask from diagnostic developers.

**Comment by senesis** [comment]
> All the tool needs to know to create a cache of script results ...is that the script ran successfully, there is no need to check that every individual output file exist

The more robust to know, when making a second run, that result files exist is to check that they are present in cache (which implies to name them)

> Unless users go and delete some script output files of course.

Cache management must occur at some stage (and may imply deleting some files), and users should have some degree of control on it


> every diagnostic developer will need to go and implement code to deal with regenerating some results and skipping others

I think that the granularity should be at the script level (I mean : a script is re-run if any of its output is missing); this does not require reworking existing scripts

**Comment by senesis** [comment]
But anyway, I propose to forget about this request. This will provide material for the report on applicability of the standard interface to CliMAF
